# Generated by Django 5.1.13 on 2025-10-28 12:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import dojo.aist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dojo", "0245_remove_test_insert_insert_remove_test_update_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISTPipeline",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("started", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("SAST_LAUNCHED", "Launched"), ("UPLOADING_RESULTS", "Uploading Results"), ("FINDING_POSTPROCESSING", "Finding post-processing"), ("WAITING_DEDUPLICATION_TO_FINISH", "Waiting Deduplication To Finish"), ("WAITING_CONFIRMATION_TO_PUSH_TO_AI", "Waiting Confirmation To Push to AI"), ("PUSH_TO_AI", "Push to AI"), ("WAITING_RESULT_FROM_AI", "Waiting Result From AI"), ("FINISHED", "Finished")], default="FINISHED", max_length=64)),
                ("launch_data", models.JSONField(blank=True, default=dict)),
                ("logs", models.TextField(blank=True, default="")),
                ("run_task_id", models.CharField(blank=True, max_length=64, null=True)),
                ("watch_dedup_task_id", models.CharField(blank=True, max_length=64, null=True)),
                ("response_from_ai", models.JSONField(blank=True, default=dict)),
                ("tests", models.ManyToManyField(blank=True, related_name="aist_pipelines", to="dojo.test")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="AISTAIResponse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("pipeline", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_responses", to="aist.aistpipeline")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="AISTProject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("supported_languages", models.JSONField(blank=True, default=list)),
                ("script_path", models.CharField(max_length=1024)),
                ("compilable", models.BooleanField(default=False)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dojo.product")),
            ],
        ),
        migrations.AddField(
            model_name="aistpipeline",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="aist_pipelines", to="aist.aistproject"),
        ),
        migrations.CreateModel(
            name="AISTProjectVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("version_type", models.CharField(choices=[("GIT_HASH", "Git commit/hash"), ("FILE_HASH", "File hash (uploaded archive)")], db_index=True, default="GIT_HASH", max_length=16)),
                ("source_archive", models.FileField(blank=True, null=True, upload_to=dojo.aist.models.AISTProjectVersion._upload_to)),
                ("source_archive_sha256", models.CharField(blank=True, default="", max_length=64, null=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="aist.aistproject")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="aistpipeline",
            name="project_version",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pipelines", to="aist.aistprojectversion"),
        ),
        migrations.CreateModel(
            name="ProcessedFinding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("finding", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dojo.finding")),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dojo.test")),
            ],
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pr_number", models.PositiveIntegerField()),
                ("base_ref", models.CharField(blank=True, max_length=255)),
                ("head_ref", models.CharField(blank=True, max_length=255)),
                ("is_from_fork", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("project_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pull_requests", to="aist.aistprojectversion")),
            ],
        ),
        migrations.AddField(
            model_name="aistpipeline",
            name="pull_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pipelines", to="aist.pullrequest"),
        ),
        migrations.CreateModel(
            name="RepositoryInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("GITHUB", "Github"), ("GITLAB", "Gitlab")], default="GITHUB", max_length=64)),
                ("repo_owner", models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Only letters, digits, dot, underscore and hyphen are allowed.", regex="^[A-Za-z0-9._-]+$")])),
                ("repo_name", models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Only letters, digits, dot, underscore and hyphen are allowed.", regex="^[A-Za-z0-9._-]+$")])),
                ("base_url", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "indexes": [models.Index(fields=["repo_owner", "repo_name", "type"], name="aist_reposi_repo_ow_86ff2b_idx")],
            },
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="repository",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pull_requests", to="aist.repositoryinfo"),
        ),
        migrations.AddField(
            model_name="aistproject",
            name="repository",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project", to="aist.repositoryinfo"),
        ),
        migrations.CreateModel(
            name="ScmGithubBinding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("installation_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("base_api_url", models.CharField(blank=True, default="", max_length=255)),
                ("scm", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="github_binding", to="aist.repositoryinfo")),
            ],
        ),
        migrations.CreateModel(
            name="ScmGitlabBinding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("personal_access_token", models.CharField(blank=True, default="", max_length=255)),
                ("scm", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="gitlab_binding", to="aist.repositoryinfo")),
            ],
        ),
        migrations.CreateModel(
            name="TestDeduplicationProgress",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pending_tasks", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("deduplication_complete", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("test", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dedupe_progress", to="dojo.test")),
            ],
        ),
        migrations.AddConstraint(
            model_name="aistprojectversion",
            constraint=models.UniqueConstraint(fields=("project", "version"), name="uniq_project_version_per_project"),
        ),
        migrations.AddIndex(
            model_name="processedfinding",
            index=models.Index(fields=["test", "finding"], name="aist_proces_test_id_38b26d_idx"),
        ),
        migrations.AddConstraint(
            model_name="processedfinding",
            constraint=models.UniqueConstraint(condition=models.Q(("finding__isnull", False)), fields=("test", "finding"), name="uniq_processed_test_finding_not_null"),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["repository", "pr_number"], name="aist_pullre_reposit_bd90c7_idx"),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(fields=("project_version", "repository", "pr_number"), name="uniq_pr_per_project_version"),
        ),
        migrations.AddIndex(
            model_name="testdeduplicationprogress",
            index=models.Index(fields=["test", "pending_tasks"], name="aist_testde_test_id_974da9_idx"),
        ),
    ]
