# Generated by Django 5.1.11 on 2025-09-08 06:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojo', '0999_test_deduplication_complete_processedfinding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISTProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('script_path', models.CharField(max_length=1024)),
                ('compilable', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
            ],
        ),
        migrations.CreateModel(
            name='AISTProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('output_dir', models.CharField(default='/tmp/aist/output', max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='aist.aistproject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AISTPipeline',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SAST_LAUNCHED', 'Launched'), ('UPLOADING_RESULTS', 'Uploading Results'), ('WAITING_DEDUPLICATION_TO_FINISH', 'Waiting Deduplication To Finish'), ('WAITING_CONFIRMATION_TO_PUSH_TO_AI', 'Waiting Confirmation To Push to AI'), ('PUSH_TO_AI', 'Push to AI'), ('WAITING_RESULT_FROM_AI', 'Waiting Result From AI'), ('FINISHED', 'Finished')], default='FINISHED', max_length=64)),
                ('launch_data', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True, default='')),
                ('run_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('watch_dedup_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('response_from_ai', models.JSONField(blank=True, default=dict)),
                ('tests', models.ManyToManyField(blank=True, related_name='aist_pipelines', to='dojo.test')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aist_pipelines', to='aist.aistproject')),
                ('project_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='aist.aistprojectversion')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddConstraint(
            model_name='aistprojectversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_project_version_per_project'),
        ),
    ]
