# Generated by Django 5.1.13 on 2025-11-12 11:53

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositoryinfo",
            name="repo_name",
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Only letters, digits, dot, underscore, hyphen and slash are allowed.", regex="^[A-Za-z0-9._/\\-]+$")]),
        ),
        migrations.AlterField(
            model_name="repositoryinfo",
            name="repo_owner",
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Only letters, digits, dot, underscore, hyphen and slash are allowed.", regex="^[A-Za-z0-9._/\\-]+$")]),
        ),
        migrations.AlterField(
            model_name="scmgitlabbinding",
            name="personal_access_token",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=""),
        ),
    ]
