# Generated by Django 5.1.11 on 2025-09-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistprojectversion',
            name='output_dir',
        ),
    ]
