# Generated by Django 5.1.13 on 2025-11-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0002_alter_repositoryinfo_repo_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aistpipeline",
            name="logs",
        ),
    ]
