# Generated by Django 5.1.11 on 2025-09-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0004_alter_aistpipeline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISTAIResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='aist.aistpipeline')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
