# Generated by Django 5.1.13 on 2026-01-23 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aist", "0005_aistpipeline_resolved_commit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdeduplicationprogress",
            name="last_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testdeduplicationprogress",
            name="last_reconcile_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testdeduplicationprogress",
            name="reconcile_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="launchschedule",
            name="launch_config",
            field=models.OneToOneField(help_text="Anchor launch config. Project is derived from launch_config.project.", on_delete=django.db.models.deletion.CASCADE, related_name="launch_schedule", to="aist.aistprojectlaunchconfig"),
        ),
        migrations.AlterField(
            model_name="pipelinelaunchqueue",
            name="launch_config",
            field=models.ForeignKey(blank=True, help_text="Launch config used to build pipeline_args snapshot.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="launch_queue_items", to="aist.aistprojectlaunchconfig"),
        ),
    ]
