# Generated by Django 5.1.11 on 2025-09-12 12:12

from django.db import migrations

def move_pipeline_json_to_history(apps, schema_editor):
    Pipeline = apps.get_model('aist', 'AISTPipeline')
    AIResp = apps.get_model('aist', 'AISTAIResponse')
    for p in Pipeline.objects.only('id','response_from_ai').iterator():
        data = getattr(p, 'response_from_ai', None)
        if isinstance(data, dict) and data:
            if not AIResp.objects.filter(pipeline_id=p.id, payload=data).exists():
                AIResp.objects.create(pipeline_id=p.id, payload=data)

class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0005_aistairesponse'),
    ]

    operations = [
        migrations.RunPython(move_pipeline_json_to_history, migrations.RunPython.noop)
    ]
