# Generated by Django 5.1.11 on 2025-09-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0006_migrate_respose_ai_data'),
        ('dojo', '1000_remove_testdeduplicationprogress_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfinding',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.finding'),
        ),
    ]
