# Generated by Django 5.1.11 on 2025-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0007_alter_processedfinding_finding'),
        ('dojo', '1000_remove_testdeduplicationprogress_test_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processedfinding',
            name='uniq_test_finding_processed',
        ),
        migrations.AddIndex(
            model_name='processedfinding',
            index=models.Index(fields=['test', 'finding'], name='aist_proces_test_id_38b26d_idx'),
        ),
        migrations.AddConstraint(
            model_name='processedfinding',
            constraint=models.UniqueConstraint(condition=models.Q(('finding__isnull', False)), fields=('test', 'finding'), name='uniq_processed_test_finding_not_null'),
        ),
    ]
