# Generated by Django 5.1.11 on 2025-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0008_remove_processedfinding_uniq_test_finding_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistproject',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
