# Generated by Django 5.1.11 on 2025-10-10 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0009_aistproject_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, digits, dot, underscore and hyphen are allowed.', regex='^[A-Za-z0-9._-]+$')])),
                ('repo_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, digits, dot, underscore and hyphen are allowed.', regex='^[A-Za-z0-9._-]+$')])),
                ('pr_number', models.PositiveIntegerField()),
                ('base_ref', models.CharField(blank=True, max_length=255)),
                ('head_ref', models.CharField(blank=True, max_length=255)),
                ('is_from_fork', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='aist.aistprojectversion')),
            ],
        ),
        migrations.AddField(
            model_name='aistpipeline',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='aist.pullrequest'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repo_owner', 'repo_name', 'pr_number'], name='aist_pullre_repo_ow_3c81a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('project_version', 'repo_owner', 'repo_name', 'pr_number'), name='uniq_pr_per_project_version'),
        ),
    ]
