# Generated by Django 5.1.11 on 2025-10-14 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0010_pullrequest_aistpipeline_pull_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('GITHUB', 'Github'), ('GITLAB', 'Gitlab')], default='GITHUB', max_length=64)),
                ('repo_owner', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, digits, dot, underscore and hyphen are allowed.', regex='^[A-Za-z0-9._-]+$')])),
                ('repo_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, digits, dot, underscore and hyphen are allowed.', regex='^[A-Za-z0-9._-]+$')])),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScmGithubBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('base_api_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScmGitlabBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_access_token', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pullrequest',
            name='uniq_pr_per_project_version',
        ),
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='aist_pullre_repo_ow_3c81a1_idx',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='repo_name',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='repo_owner',
        ),
        migrations.AddIndex(
            model_name='repositoryinfo',
            index=models.Index(fields=['repo_owner', 'repo_name', 'type'], name='aist_reposi_repo_ow_86ff2b_idx'),
        ),
        migrations.AddField(
            model_name='aistproject',
            name='repository',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='aist.repositoryinfo'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='aist.repositoryinfo'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', 'pr_number'], name='aist_pullre_reposit_bd90c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('project_version', 'repository', 'pr_number'), name='uniq_pr_per_project_version'),
        ),
        migrations.AddField(
            model_name='scmgithubbinding',
            name='scm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_binding', to='aist.repositoryinfo'),
        ),
        migrations.AddField(
            model_name='scmgitlabbinding',
            name='scm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_binding', to='aist.repositoryinfo'),
        ),
    ]
