# Generated by Django 5.1.13 on 2025-11-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0245_remove_test_insert_insert_remove_test_update_update_and_more'),
        ('dojo', '0246_endpoint_idx_ep_product_lower_host_and_more'),
    ]

    operations = [
    ]
