# Generated by Django 5.1.11 on 2025-09-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0242_file_upload_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='deduplication_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProcessedFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.finding')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.test')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('test', 'finding'), name='uniq_test_finding_processed')],
            },
        ),
        migrations.CreateModel(
            name='TestDeduplicationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_tasks', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deduplication_complete', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dedupe_progress', to='dojo.test')),
            ],
            options={
                'indexes': [models.Index(fields=['test', 'pending_tasks'], name='dojo_testde_test_id_49447b_idx')],
            },
        ),
    ]
