# Generated by Django 5.1.13 on 2025-10-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0244_pghistory_indices'),
        ('dojo', '1000_remove_testdeduplicationprogress_test_and_more'),
    ]

    operations = [
    ]
